apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zyz9i5adb-go
  janus-idp.io/tekton: zyz9i5adb-go
  backstage.io/kubernetes-id: zyz9i5adb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zyz9i5adb-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
