apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zyz9i5adb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zyz9i5adb-go 
  name: zyz9i5adb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zyz9i5adb-go 
